### ISSUE TITLE
terragrunt support needed

### ISSUE THREAD

**Issue by DevOps575** [terraform-linters/tflint#119]
Hi,

This is an awesome wrapper to perform the lint analysis on terraform code. In my case we are using terragrunt wrapper to perform the terraform activities.

We were trying to use tflint for terragrunt but it seems tflint does not support terragrunt semantics. Is it possible to add the support for terragrunt?

It will be a great enhancement.

Thanks,
Sanjiv

**Comment by wata727** [comment]
Hi @jkumar19, Thanks for your suggestion.
But, I've not even completed Terraform support yet... So, I'm going to focus on it.
If you have a implementation about that, the patches are welcome :)

**Comment by babilen5** [comment]
Thank you, @wata727, for this very useful tool.

I was wondering if you managed to look into terragrunt support in the interim as it would indeed be very helpful.

**Comment by wata727** [comment]
In fact, I'm not familiar with Terragrunt, so I'm not sure under what cases TFLint does not work.

If anyone shares a specific situation, I might be able to consider a solution. However TFLint heavily depends on Terraform's internal APIs, so it may be difficult to keep supporting Terragrunt extensions at the same time...

**Comment by ashemedai** [comment]
@wata727 Terragrunt essentially wraps Terraform, so in the basis most of it remains the same. The easiest way forward is to make sure the `modules/*/*.tf` files can be linted without problems. And that's just plain TF. The other files that Terragrunt uses are HCL files and these are the ones that use the modules. They tend to be very "thin", e.g.:

```
terraform {
  source = "../../modules//infrastructure"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  netblock_cidr            = "10.10.0.0/16"
  public_netblock_cidr     = "10.10.0.0/20"
  api_netblock_cidr        = "10.10.16.0/20"
  functions_netblock_cidr  = "10.10.32.0/20"
  management_netblock_cidr = "10.10.48.0/20"
  private_netblock_cidr    = "10.10.64.0/18"
  database_netblock_cidr   = "10.10.128.0/19"
}
```

**Comment by bendrucker** [comment]
Terragrunt is focused on reducing Terraform boilerplate by generating root modules at runtime and then calling through to `terraform` by invoking its CLI. It provides constructs for generating repetitive root configuration (providers, backends) as well as module calls. Terragrunt's mode of operation (exec-ing `terraform`) is dissimilar from TFLint, which relies on Terraform's _libraries_ for loading and parsing configuration and not the Terraform CLI.

<hr>

### Child modules

You can run TFLint on your child modules. Anything you're putting in `terraform.source` in your Terragrunt config should be something TFLint can evaluate. 

### Root modules

At the moment, the only option seems to be to use hooks to run TFLint before or after Terraform commands. You could invoke TFLint before `plan` and `apply` and/or after `validate`.

However, you'd find that TFLint is not able to evaluate Terragrunt's inputs and thus enabling `--modules` is less useful than expected. The map of `inputs` is written to a JSON file and passed to relevant Terraform via `--var-file`. Terragrunt can also generate arbitrary Terraform arguments for certain commands, allowing you to pass additional `--var-file` flags (or `-var`).

<hr>

Terragrunt could add support for invoking binaries other than Terraform, perhaps something like `exec` and `exec-all`. This would help support any Terraform static analysis tool. TFLint, by using `-var-file` and `-var` flags to match Terraform, seems to be doing everything it can to be interoperable.

Since there's no clear action for TFLint to take here, I'm going to go ahead and close this issue. If Terragrunt users want to contribute docs that's welcome, otherwise at least this issue is searchable for anyone wondering. If Terragrunt does pursue invoking commands other than `terraform`, then I can definitely see documenting a recommended setup.

**Comment by babilen5** [comment]
A simple way of running tflint in terragrunt is by adding a block such as the following:

**Comment by babilen5** [comment]
A simple way of running tflint with terragrunt is to add a block such as the following:

```
terraform {
  before_hook "before_hook" {
    commands = ["validate"]
    execute  = ["tflint", "."]
  }
}
```
This would run `tflint` whenever you execute `terragrunt validate` or `terragrunt validate-all`. You can similarly configure it for `plan` and  `apply` simply by adding those to `commands = [...]` in the `before_hook` configuration.
