### ISSUE TITLE
Check for tags rule

### ISSUE THREAD

**Issue by mateusduboli** [terraform-linters/tflint#150]
Check for AWS resources which are tagable but doesn't have any tags specified.

A bonus point would be to check for specific tag keys like `Name` and `Team`.

**Comment by wata727** [comment]
@mateusduboli Thanks for your suggestion!

However, I think that whether to specify tags on resources depends on a project. For that reason, I think that you should use [terraform_validate](https://github.com/elmundio87/terraform_validate) etc. that you can define rules yourself in such cases. WDYT?

**Comment by mateusduboli** [comment]
Thanks for the suggestion!
But my doubt would be why not include in `tflint` too?

**Comment by cristim** [comment]
I also +1 this, I  see no harm in tflint having this as well, much like pylint overlaps some of the pep8 rules for python code.

The key is to carefully implement the rules so that they don't conflict with the other tools in the default configuration.

The reality is that there are usually multiple choices and it is not always easy to cleanly segment their scope. Some users will only run one of those but still expect some decent support.

**Comment by aferg439** [comment]
+1 from me, as well. Is this still being tracked? We'd love to implement this tool in our automation to check for tagging of resources where applicable. There's only so much that can be forced through modules.

**Comment by wata727** [comment]
Now I think implementing this is not a bad option. We will implement it if necessary.

**Comment by aferg439** [comment]
There aren't a whole lot of options out there that accomplish this. It would definitely be a win for the community.

**Comment by wata727** [comment]
Closed this in #617
