### ISSUE TITLE
Enable local module inspection by default

### ISSUE THREAD

**Issue by wata727** [terraform-linters/tflint#1502]
## Introduction

Currently, module inspection is disabled by default. This is because it needs to run `terraform init` to build the module tree. This decision was made to lower the hurdles for using TFLint as much as possible.

But for local modules, this assumption is not true. You can access the module content without running `terraform init`. Previously, local modules were built from the module manifest file just like any other module, so it was difficult to enable only local modules by default.

## Proposal

By redesigning the Loader, the module tree can be built for local modules even without a module manifest file.

Change `buildChildModules` to move Loader's `LoadModule` logic under the terraform package.
https://github.com/terraform-linters/tflint/blob/v0.39.3/terraform/config.go#L64-L112
https://github.com/terraform-linters/tflint/blob/v0.39.3/tflint/loader.go#L222-L277

## References

https://github.com/terraform-linters/tflint/blob/v0.39.3/terraform/config.go#L64-L112
https://github.com/terraform-linters/tflint/blob/v0.39.3/tflint/loader.go#L222-L277

**Comment by raymondchen625** [comment]
+1.
`--recursive` doesn't work very well in the local-module scenario. To avoid `terraform_required_providers` and `terraform_required_version` warnings, I have to put a copy of the `terraform` block in all my local modules. That's unnecessary and hard to maintain.
Because my `tflint` runs in CI and the terraform backend is remote, it's not practical to grant CI runner access to the remote backend to run `terraform init`. Local module inspection would be a nice feature.

**Comment by bendrucker** [comment]
Doesn't seem like either case is dependent on this feature.

`required_providers` is required in all modules. You may choose to leave the `version` unset in some modules and inherit it from the parent. You cannot leave `source` unset, except for providers in the `hashicorp` namespace, for which `required_providers` is always technically optional.

This feature would simply act like `--recursive`, but walk the graph of `module` calls instead of a directory. So if your goal is having rules that behave differently for child modules, that's not necessarily covered here.

`terraform init -backend=false` is a thing for getting your modules. So lack of backend credentials shouldn't be stopping anyone from using module mode.

**Comment by raymondchen625** [comment]
> `terraform init -backend=false` is a thing for getting your modules. So lack of backend credentials shouldn't be stopping anyone from using module mode.

Thanks for pointing out the `-backend=false` option. It seems I shouldn't use `--module` at all. Module inspection only checks the module's input variables.
My requirement is check those local module subdirectories like it checks the root but skipping the rules on `terraform_required_providers` and `terraform_required_version`. I could do it by putting a `.tflint.hcl` in those subdirecotries with:
```
rule "terraform_required_providers" {
  enabled = false
}
rule "terraform_required_version" {
  enabled = false
}
```

**Comment by acdha** [comment]
Two other wrinkles which I ran into. My goal was to have my submodules linted along with the top-level code but this turns out to be somewhat tedious:

1. Using the `tflint-bundle` container, `--module` is not an option without modifying it to install the Terraform binary.
2. Using `--recursive` means that variables which are used as inputs, etc. will be reported as unused (i.e. `tflint --recursive --fix` is unsafe). Using `--module` means that only the inputs will be validated.

It feels like what I really want is a hybrid of the two approaches where tflint would examine every line of Terraform code in my Git repository but not require that remote modules be installed.

**Comment by wata727** [comment]
That's exactly right. With the current TFLint mechanism, there is no easy way to perform module inspections recursively, but this change should make it possible for local modules.
