### ISSUE TITLE
Support for additional providers

### ISSUE THREAD

**Issue by mrala** [terraform-linters/tflint#175]
Are there plans to extend support for additional providers like Azure or Google Cloud?

**Comment by mmclane** [comment]
+1

**Comment by wata727** [comment]
Maybe it is possible. However, I'm not familiar with providers other than AWS, so there are no plans for now.

**Comment by thejmazz** [comment]
Can you outline how the current code does this? I might be able to dedicate a few cycles towards adding OpenStack support!

**Comment by jeff-knurek** [comment]
I was so excited when https://github.com/wata727/tflint/issues/167 got closed, only to find that we still can't make use of this tool because the providers are not supported 😢

**Comment by wata727** [comment]
Umm... I believe that additional provider support is needed, but a big challenge is how to keep the rules up-to-date. In order to forget the problem once, I think that the first step is to provide a plugin system so that each one can freely add rules.

I'm now waiting for a response from the first plugin system author. See #255
If there is no response, it may be better for me or someone else to start implementing the plugin system instead.

**Comment by wata727** [comment]
Hi all 👋 

TFLint v0.14.0 implemented an experimental plugin system to support other providers. First of all, I have created repositories to start supporting major clouds.
https://github.com/terraform-linters/tflint-ruleset-google
https://github.com/terraform-linters/tflint-ruleset-azurerm

See also #606 for details.
