### ISSUE TITLE
Naming convention rules

### ISSUE THREAD

**Issue by nijave** [terraform-linters/tflint#273]
Are there any plans to implement https://www.terraform-best-practices.com/naming / https://www.terraform.io/docs/extend/best-practices/naming.html

I think it's pretty standard for linters, in general, to enforce certain conventions so it would be nice if tflint did this

**Comment by wata727** [comment]
Thanks for opening the issue, @nijave 

I still thinking about how to handle such convention rules. Originally, TFLint was developed to prevent `terraform apply` failing. Perhaps those that find possible errors and those that enforce the naming convention have different goals.

One answer is to disable all rules by default like ESLint and make it completely a pluggable linter. Or, like ESLint and Prettier, it might be better to separate the tools by goals.

As my current motivation is to improve the detection accuracy of possible errors, unfortunately, such rules may not be implemented for a while. FWIW, there is an idea to introduce a plugin system in #255, so it may be useful.

**Comment by stephencroberts** [comment]
@wata727 I'm most interested in static analysis on terraform code for things like formatting, naming conventions, type checks (warn/error for untyped variables or for using general types), etc. Do you believe this project should support those types of rules? I'm willing to contribute and haven't come across any other tool that's close, but want to make sure it's the right fit.

**Comment by wata727** [comment]
@stephencroberts Yes. I believe that TFLint should be a platform for inspecting Terraform code. However, there are currently no plans to deal with issues covered by other tools (like `terraform validate`, `terraform plan`).

On the other hand, I'm wondering how to add those rules. I'm now focusing on possible error rules because to make the rules that are enabled by default sense to many users.

I think it's probably a good idea to add it as a disabled rule by default or add it as a plugin separately.

**Comment by wata727** [comment]
Implemented naming convention rules.
https://github.com/terraform-linters/tflint/blob/v0.16.2/docs/rules/terraform_naming_convention.md
