### ISSUE TITLE
[Feature Request] Alphabetical sort

### ISSUE THREAD

**Issue by smiller171** [terraform-linters/tflint#783]
I'd love to be able to enforce alphabetical sorting, especially of variable declarations in `variables.tf` but also of parameters within blocks (while keeping single-line declarations above block declarations)

**Comment by bendrucker** [comment]
Pull request welcome here. This is now possible through the use of:

https://pkg.go.dev/github.com/terraform-linters/tflint@v0.16.1/tflint?tab=doc#Runner.Files
https://pkg.go.dev/github.com/terraform-linters/tflint@v0.16.1/tflint?tab=doc#Runner.WalkExpressions

**Comment by bendrucker** [comment]
On second thought, you will need `runner.Files` but you can't accomplish this by walking expressions. 

It's also going to be a real struggle to implement this for attributes. Variable blocks are easier, since HCL [`Blocks`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.5.1?tab=doc#Blocks) are ordered. [`Attributes`](https://pkg.go.dev/github.com/hashicorp/hcl/v2@v2.5.1?tab=doc#Attributes) are unordered (and Go enforces random map iteration). You'd have to get pretty low level (into hclsyntax) to accomplish this.

Also, FWIW, I would not personally endorse alphabetic sorting of configuration. I encourage my team to use logical grouping where appropriate, i.e. grouping like attributes/blocks and delimiting with newlines. Sometime I'll include a comment to help advertise these groupings, e.g.:

```tf
# general

variable "a" {

}

variable "b" {

}

# networking

variable "c" {

}

variable "d" {

}

# compute

variable "e" {

}

variable "f" {

}
```

Terraform's docs are not alphabetized and tend to use logical attribute grouping. Obviously feel free to keep your own convention, mentioning because:

* The "market" for this rule may be pretty small relative to other core rules
* While I'm very keen on expanding TFLint's ability to enforce syntax rules (e.g. [`terraform_comment_syntax`](https://github.com/terraform-linters/tflint/blob/master/docs/rules/terraform_comment_syntax.md) I'm not going to tackle this particular rule.

**Comment by bendrucker** [comment]
Closing as there's no plan/intent to implement this and there are notable technical barriers

**Comment by wyardley** [comment]
Enforcing alphasort in lists or object keys would be a great (non-default, but optional) linter rule IMO. I may make a separate feature request for that, though I'm not sure I have the time / skills to implement it myself in the short term.

(side note: sorting alphabetically by resource name doesn't always make sense, but IMO, it can make good sense in certain contexts, such as you already have things broken down in files / directories in such a way that you have
