### ISSUE TITLE
Ability to require specific parameter (tags)

### ISSUE THREAD

**Issue by krzysztof-magosa** [terraform-linters/tflint#984]
Hi.
We were investigating `aws_resource_missing_tags`, but due to lack of parsing local values it's unusable in our use case at the moment. Would be great if there was possibility to just require having `tags` set to any value - this way we could support at least situations when somebody misses tags at all. Not sure existing `aws_resource_missing_tags` could be extended to do so, or maybe it would be better to create separate generic module which would allow to require setting arbitrary parameters on specific types of resources? If maintainer/author could advise on desired way of implementation I can try contributing code.
Thanks.

**Comment by bendrucker** [comment]
I don't think this rule is a particularly good fit for TFLint's core Terraform rule set. The goal for existing rules is generally to be useful out of the box with sane defaults that enforce a specific best practice. It's also not not really suitable for the AWS set since it's generic.

Have a look at the plugin docs, that's the best way to go about introducing a custom rule:

https://github.com/terraform-linters/tflint/blob/master/docs/guides/extend.md

At some point the two core rules packages (terraform, aws) will move to separate plugins as well.
